'use strict';
const $=id=>document.getElementById(id);
let token=location.hash.slice(1),state=null,draft=null,busy=false,fresh=false,selection=null,proposalArtifact=null,outputCounter=0;
history.replaceState(null,'',location.pathname);
const put=(id,text)=>$(id).textContent=text;
const states={SIGNED_PENDING_INCLUSION:'已签名 · 等待当地入块',INCLUDED_IN_LOCAL_LEDGER:'已进入当地账本',EXPIRED_BEFORE_INCLUSION:'未入块签名已过期',INPUTS_CONSUMED_BY_OTHER_LOCAL_COMMAND:'输入已被其他当地付款消费'};
const receiptStates={VERIFIED_EVIDENCE_PENDING_IMPORT:'证据已核验 · 等待导入',IMPORT_ACCEPTED_IMMATURE:'当地已导入 · 等待成熟',ORIGINAL_OUTPUT_SPENDABLE:'原收款输出已成熟可花',ORIGINAL_OUTPUT_SPENT:'原收款输出已花费',QUARANTINED:'受冲突影响 · 已隔离'};
function node(tag,text,kind){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(kind)e.className=kind;return e}
function message(text,error=false){put('message',text);$('message').hidden=false;$('message').classList.toggle('error',error)}
function friendly(text){if(/state changed|stale|rollback|head differs/i.test(text))return '账本或保留记录已改变。请刷新并重新预览；若仍失败，请保留数据目录重新核验。';if(/authorize|approval|contribution|intent/i.test(text))return '签名不足、内容不一致或付款不再有效。请重新核对各方批准。';return text}
async function request(action,values={}){const response=await fetch('/api',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({action,...values}),cache:'no-store',signal:AbortSignal.timeout(35000)});const result=await response.json();if(!response.ok)throw Error(friendly(result.error||'本机核验未完成'));return result}
function availability(){document.querySelectorAll('form button').forEach(b=>b.disabled=busy||!fresh||!!state?.wallet?.local_region_quarantined);$('sign').disabled=busy||!fresh||!$('reviewed').checked||!state?.signing_enabled||!!state?.wallet?.local_region_quarantined;$('refresh').disabled=busy;$('backup').disabled=busy||!fresh||!state?.backup_enabled||!state?.wallet;$('download-proposal').disabled=busy;document.querySelectorAll('.history-item button, #combined button').forEach(b=>b.disabled=busy||!fresh);if(selection&&state?.wallet&&!selectionCurrent())$('build-proposal').querySelector('button:not([type=button])').disabled=true;if($('group-outputs').children.length>=16)$('add-output').disabled=true}
async function task(fn){if(busy)return;busy=true;availability();try{await fn()}catch(error){message(error.message,true);if($('review-dialog').open){$('review-dialog').close();draft=null;$('reviewed').checked=false}if(state)try{await refresh()}catch{}}finally{busy=false;availability()}}
function details(target,rows){target.replaceChildren();for(const [label,text] of rows)target.append(node('dt',label),node('dd',String(text)))}
function download(name,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}
function button(label,fn){const b=node('button',label,'secondary');b.type='button';b.onclick=()=>task(fn);return b}
function integer(value){if(!/^[0-9]+$/.test(value)||value.length>39)throw Error('请输入有效的非负整数金额');return BigInt(value)}
function options(id,regions,exclude){const previous=$(id).value;$(id).replaceChildren();for(const r of regions){if(r.id===exclude)continue;const o=node('option',r.name+(r.id===state.context.region?' · 本地区':''));o.value=r.id;$(id).append(o)}if(regions.some(r=>r.id===previous&&r.id!==exclude))$(id).value=previous}
let savedBackupHead=null;
function render(s){if(savedBackupHead&&savedBackupHead!==s.wallet?.wallet_head){$('backup-result').hidden=true;savedBackupHead=null}state=s;fresh=true;document.body.classList.remove('stale');$('wallet').hidden=!s.wallet;$('start').hidden=!!s.wallet;put('freshness','本机已核验 · '+new Date(s.checked_at_unix*1000).toLocaleString()+(s.wallet?' · 当地高度 '+s.wallet.ledger.pin.height:''));if(s.recovery_notice)message(s.recovery_notice);if(!s.wallet)return;if(s.wallet.incident_ids.length)message('检测到已验证冲突：受影响的资产与出口已隔离，历史记录继续保留。',true);put('custody-mode',s.encrypted_key_enabled?'密钥已在本机终端解锁，浏览器不接收密钥或密码。':'当前使用启动时选定的本机密钥。加密备份需要启用加密密钥并指定本机备份目录。');const w=s.wallet,l=w.ledger;put('available',w.available);put('reserved',w.reserved_owned_outputs);put('immature',l.immature);put('quarantined',l.quarantined);put('onward',w.available_onward_export);put('owner',s.owner);put('region-name',s.context.regions.find(r=>r.id===s.context.region)?.name||s.context.region);details($('domains'),[['货币根',s.context.currency],['本地区',s.context.region],['当前区块',l.pin.tip],['当地终局',l.pin.finality||'尚未安装当地终局']]);options('destination',s.context.regions);options('group-destination',s.context.regions);if(!$('participants').value)$('participants').value=s.owner;options('source',s.context.regions,s.context.region);if(!$('receipt-owner').value)$('receipt-owner').value=s.owner;remoteFields();
const list=$('history');list.replaceChildren();if(!w.signed.length)list.append(node('p','尚无已签名付款','small'));for(const h of w.signed){const item=node('div',undefined,'history-item');item.append(node('span',h.quarantined?'受冲突影响 · 保留历史，暂停相关付款':h.local_export_finalized?'源地区出口已终局 · 目的到账仍需当地核验':states[h.state]||h.state,'stage'));const i=h.intent;item.append(node('p',i.remote?'跨地区毛额 '+i.remote.amount+' · 目的费用 '+i.destination_fee:'当地付款 '+i.outputs.map(p=>p.amount).join(' + ')));item.append(node('div',h.intent_id,'hash'));if(!h.retained_approvals_complete)item.append(node('p','本机保留的是本人的部分批准；其他所有者是否已签名仍需核对。','small'));if(i.remote)item.append(node('p','源端尚不能确认目的地区是否导入；运输保管回执不代表到账。','small'));const actions=node('div',undefined,'actions');actions.append(button('恢复并下载签名',async()=>download('rld-signature-'+h.intent_id.slice(0,12)+'.json',(await request('recover',{intent:h.intent_id})).commands)));if(s.local_block_producer_enabled&&h.retained_approvals_complete&&h.state==='SIGNED_PENDING_INCLUSION')actions.append(button('提交到当地账本',async()=>{await request('submit',{intent:h.intent_id});message('已完成当地入块。跨区出口仍须等待当地终局。');await refresh()}));item.append(actions);list.append(item)}
const net=$('network');net.replaceChildren();if(!s.transport){net.append(node('p','尚无本机接触报告。远方可达性未知。','small'))}else{const t=s.transport.observation;net.append(node('p','已学习身份 '+t.nodes+' · 候选路由 '+Object.values(t.routes||{}).filter(Boolean).length));net.append(node('p','保留运输记录 '+Object.keys(t.messages||{}).length));net.append(node('p','历史报告时间：'+new Date(s.transport.reported_at_unix*1000).toLocaleString(),'small'));const tcp=t.tcp?.observations||{};net.append(node('p','历史接触观测 '+Object.keys(tcp).length+' · 当前进程存活尚未核验','small'))}groupBudget();availability()}
async function refresh(){try{render(await request('status'))}catch(error){fresh=false;document.body.classList.add('stale');put('freshness',state?'保留上次核验数据 · 当前无法核验，付款已暂停':'当前无法核验本机钱包');availability();throw error}}
function remoteFields(){if(!state)return;const remote=$('destination').value!==state.context.region;$('remote-fields').hidden=!remote;try{const net=integer($('amount').value)-integer($('destination-fee').value);put('net-estimate','预计收款净额：'+(net>0n?net:'—')+' runlai（尚未到账）')}catch{put('net-estimate','远方收件人获得付款金额减去目的地区费用的净额。')}}
function reviewRows(p){const d=p.draft,i=d.intent;const rows=[['货币根',i.currency],['来源地区',i.region],['目的地区',i.destination||'当地付款'],['当前当地高度',d.pin.height],['有效至当地高度',i.valid_through],['输入总额',d.selected_input_total],['当地费用',i.fee],['自动找零',d.change]];for(const input of i.inputs)rows.push(['输入',input+'\n所有者：'+d.input_owners[input]+'\n金额：'+d.input_amounts[input]]);for(const o of i.outputs)rows.push(['当地支付 / 退款',o.owner+'\n金额：'+o.amount]);if(i.remote)rows.push(['远方接收者',i.remote.owner],['远方毛额',i.remote.amount],['目的费用',i.destination_fee],['远方净额',BigInt(i.remote.amount)-BigInt(i.destination_fee)]);rows.push(['实际必要所有者',Array.from(new Set(Object.values(d.input_owners))).sort().join('\n')],['付款编号',d.intent_id]);return rows}
function showReview(prepared){draft=prepared;proposalArtifact=prepared.proposal||null;$('download-proposal').hidden=!proposalArtifact;details($('review-details'),reviewRows(draft));$('reviewed').checked=false;availability();$('review-dialog').showModal()}
async function prepare(value){showReview(await request('prepare',{request:value}))}
async function fileJSON(file){if(!file||file.size>2*1024*1024)throw Error('请选择不超过 2 MiB 的 JSON 文件');return JSON.parse(await file.text())}
$('refresh').onclick=()=>task(refresh);$('initialize').onclick=()=>task(async()=>render(await request('init')));$('copy-owner').onclick=()=>task(async()=>{await navigator.clipboard.writeText(state.owner);message('已复制完整收款公钥。')});$('destination').onchange=remoteFields;$('amount').oninput=remoteFields;$('destination-fee').oninput=remoteFields;
$('payment').onsubmit=e=>{e.preventDefault();task(async()=>{const amount=integer($('amount').value).toString(),fee=integer($('fee').value).toString(),remote=$('destination').value!==state.context.region;await prepare({owner:state.owner,inputs:null,outputs:remote?[]:[{owner:$('recipient').value,amount}],remote:remote?{destination:$('destination').value,recipient:{owner:$('recipient').value,amount},destination_fee:integer($('destination-fee').value).toString()}:null,fee,valid_for_blocks:Number($('expiry').value)})})};
$('group').onsubmit=e=>{e.preventDefault();task(async()=>{const proposal=await fileJSON($('proposal').files[0]);showReview(await request('proposal-review',{proposal}))})};
$('combine').onsubmit=e=>{e.preventDefault();task(async()=>{const files=Array.from($('contributions').files);if(!files.length||files.length>16)throw Error('请选择至多 16 份所有者签名');const parts=[];for(const f of files){const v=await fileJSON(f);parts.push(...(Array.isArray(v)?v:v.commands||[]))}const result=await request('combine',{contributions:parts});const c=$('combined');c.hidden=false;c.replaceChildren();c.append(node('p','全部必要批准已通过当前原生核验；尚未入块。'));c.append(node('div',result.intent_id,'hash'));c.append(button('下载完整付款',async()=>download('rld-combined-'+result.intent_id.slice(0,12)+'.json',result.commands)));if(state.local_block_producer_enabled)c.append(button('提交组合付款到当地账本',async()=>{await request('submit-combined',{combined_id:result.combined_id});message('组合付款已进入当地账本。');c.replaceChildren(node('p','组合付款已进入当地账本。'));await refresh()}))})};
$('download-proposal').onclick=()=>task(async()=>{if(!proposalArtifact)throw Error('尚未生成提案');download('rld-proposal-'+proposalArtifact.intent_id.slice(0,12)+'.json',proposalArtifact);message('已下载未签名提案；提案不预留输入，也不代表各方已批准。')});$('reviewed').onchange=availability;$('cancel').onclick=()=>task(async()=>{const id=draft?.review_id;draft=null;$('review-dialog').close();if(id)await request('cancel-review',{review_id:id});await refresh()});$('review-dialog').addEventListener('cancel',e=>{e.preventDefault();$('cancel').click()});
$('sign').onclick=()=>task(async()=>{if(!draft||!$('reviewed').checked)throw Error('请先完成审阅');const result=await request('sign',{review_id:draft.review_id,review_commitment:draft.review_commitment});draft=null;$('review-dialog').close();message(result.retained_approvals_complete?'签名已保存，输入已预留。尚未入块；可在记录中提交或下载。':'你的部分签名已保存，只预留你的输入。下载后交给其他参与者组合。');await refresh()});
$('receipt').onsubmit=e=>{e.preventDefault();task(async()=>{const r=await request('receipt',{expectation:{currency:state.context.currency,source:$('source').value,destination:state.context.region,export:$('export').value,recipient:$('receipt-owner').value,net_amount:integer($('net').value).toString()}});const c=$('receipt-result');c.hidden=false;c.className='receipt-state';c.replaceChildren();c.append(node('strong',r.quarantined?'已隔离 · 暂不可花':receiptStates[r.state]||r.state));const dl=node('dl',undefined,'review');details(dl,[['独立证据验证',r.evidence_verified?'已通过':'未通过'],['账本导入',r.import_accepted?'当地已接受':'等待当地导入'],['成熟高度',r.mature_height??'未确定'],['原输出剩余',r.original_output_remaining],['原输出当前可花',r.original_output_spendable_now?'是':'否'],['再出口终局',r.local_finality_covers_import?'当地终局已覆盖':'尚未覆盖'],['来源是否获知回执','未知；不影响当地成熟收款']]);c.append(dl)})};

function pinEqual(a,b){return !!a&&!!b&&Object.keys(a).length===Object.keys(b).length&&Object.keys(a).every(k=>a[k]===b[k])}
function selectionCurrent(){return !!selection&&pinEqual(selection.pin,state?.wallet?.ledger.pin)&&selection.wallet_head===state?.wallet?.wallet_head}
function selectedCoins(){if(!selection)return [];return Array.from($('proposal-inputs').querySelectorAll('input:checked')).map(i=>({id:i.value,...selection.owners.flatMap(o=>o.coins.map(c=>({...c,owner:o.owner}))).find(c=>c.id===i.value)}))}
function coinEligible(c){return !c.reserved_by_this_wallet&&($('group-destination').value===state.context.region?c.spendable_now:c.eligible_for_onward_export)}
function addOutput(){if($('group-outputs').children.length>=16)throw Error('至多填写 16 笔当地支付 / 退款');const row=node('div',undefined,'output-row'),number=++outputCounter;const owner=node('input');owner.id='output-owner-'+number;owner.className='output-owner';owner.required=true;owner.pattern='[0-9a-f]{64}';owner.maxLength=64;owner.spellcheck=false;const amount=node('input');amount.id='output-amount-'+number;amount.className='output-amount';amount.required=true;amount.inputMode='numeric';amount.pattern='[0-9]+';const label=node('label','当地接收者 / 退款所有者');label.htmlFor=owner.id;const amountLabel=node('label','明确金额 · runlai');amountLabel.htmlFor=amount.id;const remove=node('button','移除此输出','secondary');remove.type='button';remove.onclick=()=>{row.remove();groupBudget();availability()};row.append(label,owner,amountLabel,amount,remove);owner.oninput=groupBudget;amount.oninput=groupBudget;$('group-outputs').append(row)}
function proposalValues(){if(!selectionCurrent())throw Error('账本或钱包预留已改变；请重新读取输入。');const coins=selectedCoins();if(!coins.length||coins.length>16||coins.some(c=>!coinEligible(c)))throw Error('请选择至多 16 个符合当前付款条件的输入。');const participants=Array.from(new Set(coins.map(c=>c.owner))).sort();if(participants.length<2||!participants.includes(state.owner))throw Error('请选择本人和至少另一位参与者的实际输入。');const remote=$('group-destination').value!==state.context.region;return {owner:state.owner,participants,inputs:coins.map(c=>c.id).sort(),outputs:Array.from($('group-outputs').children).map(row=>({owner:row.querySelector('.output-owner').value,amount:integer(row.querySelector('.output-amount').value).toString()})),remote:remote?{destination:$('group-destination').value,recipient:{owner:$('group-recipient').value,amount:integer($('group-amount').value).toString()},destination_fee:integer($('group-destination-fee').value).toString()}:null,fee:integer($('group-fee').value).toString(),valid_for_blocks:Number($('group-expiry').value)}}
function groupBudget(){if(!selection)return;const remote=$('group-destination').value!==state.context.region;$('group-remote').hidden=!remote;for(const input of $('proposal-inputs').querySelectorAll('input')){const coin=selection.owners.flatMap(o=>o.coins).find(c=>c.id===input.value);input.disabled=!coinEligible(coin)&&!input.checked}if(!selectionCurrent()){put('proposal-budget','账本或钱包预留已改变；请重新读取输入。');return}try{const total=selectedCoins().reduce((a,c)=>a+integer(c.amount),0n);const local=Array.from($('group-outputs').children).reduce((a,row)=>a+integer(row.querySelector('.output-amount').value),0n);const used=local+integer($('group-fee').value)+(remote?integer($('group-amount').value):0n);put('proposal-budget','所选输入 '+total+' · 明确支付与费用 '+used+' · '+(total===used?'金额相等，仍需原生核验。':total>used?'请明确剩余 '+(total-used)+' 的退款归属。':'还缺少 '+(used-total)+' 的输入。'))}catch{put('proposal-budget','请填写完整的明确金额；不会自动分配找零。')}}
$('load-inputs').onsubmit=e=>{e.preventDefault();task(async()=>{await refresh();const owners=$('participants').value.split(/\s+/).filter(Boolean);if(owners.some(o=>!/^[0-9a-f]{64}$/.test(o))||new Set(owners).size!==owners.length)throw Error('请填写不同的完整公钥，每行一个。');selection=await request('proposal-inputs',{owners:owners.sort()});const box=$('proposal-inputs');box.replaceChildren();box.hidden=false;for(const o of selection.owners){box.append(node('p',(o.owner===state.owner?'你':'参与者')+' · '+o.owner,'proposal-owner'));if(!o.coins.length)box.append(node('p','当前没有原生未花输出。','small'));for(const coin of o.coins){const label=node('label',undefined,'coin-option'),check=node('input');check.type='checkbox';check.value=coin.id;check.onchange=()=>{groupBudget();availability()};const stage=coin.reserved_by_this_wallet?'本人已预留':coin.quarantined?'已隔离':!coin.spendable_now?'尚未成熟':coin.eligible_for_onward_export?'可用于当地 / 跨区付款':'可用于当地付款，尚未满足再出口终局';label.append(check,node('span',coin.amount+' runlai · '+stage+'\n'+coin.id));box.append(label)}}$('build-proposal').hidden=false;groupBudget();message('已读取当地账本输入。其他钱包的私有预留未知，各方仍须独立核验。')})};
$('add-output').onclick=()=>task(async()=>{addOutput();groupBudget()});$('group-destination').onchange=()=>{groupBudget();availability()};for(const id of ['group-amount','group-destination-fee','group-fee'])$(id).oninput=groupBudget;
$('build-proposal').onsubmit=e=>{e.preventDefault();task(async()=>{showReview(await request('proposal-build',{request:proposalValues(),selection_pin:selection.pin}))})};

if(!/^[0-9a-f]{64}$/.test(token)){message('请使用本机钱包启动时显示的完整会话链接。刷新页面后需重新使用该链接打开。',true);fresh=false;availability()}else{task(refresh);setInterval(()=>{if(!busy&&!$('review-dialog').open)refresh().catch(error=>message(error.message,true))},5000)}

$('backup').onclick=()=>task(async()=>{const r=await request('backup');savedBackupHead=r.wallet_head;details($('backup-result'),[['加密备份已保存',r.saved_file],['请另行保留最新钱包指纹',r.wallet_head]]);$('backup-result').hidden=false;message('备份已保存。请将最新钱包指纹另行保管；签署新付款后需要更新备份。')});
