# Load in nginx's http context once; shared by retired/testnet site locations.
limit_req_zone $binary_remote_addr zone=rld_read:10m rate=6r/s;
limit_conn_zone $binary_remote_addr zone=rld_read_conn:10m;
